# ===============================
# APPLICATION
# ===============================
spring.application.name=metro-ticket-system

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# DATABASE (NEON CLOUD DB)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-gentle-tree-aow3vlj5-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_he0HGnfvxs4u
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# DEBUG
# ===============================
logging.level.org.hibernate.type.descriptor.sql=TRACE